[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
predictx-shared = { workspace = true }
poll-factory = { path = "../../contracts/poll-factory" }
voting-oracle = { path = "../../contracts/voting-oracle" }
